### ISSUE TITLE
DTLS with IKEA Tradfri Gateway

### ISSUE THREAD

**Issue by chkr1011** [kmiller77/DTLS2.Net#1]
Hi,
I am trying to connect with a IKEA Tradfri Gateway. I am building my own CoAP library at the moment which makes use of this DTLS library.

But unfortunately I cannot connect with the gateway and even with a linux test coap server (coap-server). I am no protocol expert for DTLS so I am giving you as much information as I can.

My code looks like this (You can assume that the CoAP generation is properly implemented).

```csharp
var ikeaGatewayEndpoint = new IPEndPoint(IPAddress.Parse("192.168.1.243"), 5684);

Console.WriteLine("CONNECTING...");

using (var dtlsClient = new DTLS.Client(new IPEndPoint(IPAddress.Any, 1)))
{
    dtlsClient.SetVersion(new Version(1, 2));
    dtlsClient.PSKIdentities.AddIdentity(Encoding.ASCII.GetBytes("Client_identity"), Encoding.ASCII.GetBytes("KEY"));

    await dtlsClient.ConnectToServerAsync(ikeaGatewayEndpoint);

    Console.WriteLine("CONNECTED");

    var optionBuilder = new CoapMessageOptionFactory();

    var message = new CoapMessage
    {
        Type = CoapMessageType.Confirmable,
        Code = CoapMessageCodes.Get,
        Id = 0x1234,
    };

    message.Options.Add(optionBuilder.CreateUriPath("15011"));

    var messageEncoder = new CoapMessageEncoder();
    var buffer = messageEncoder.Encode(message);

    Console.WriteLine("SENDING REQUEST");

    var response = await dtlsClient.SendAndGetResponseAsync(buffer.ToArray(), TimeSpan.FromSeconds(5));

    Console.WriteLine("RESPONSE RECEIVED");
}

Console.ReadLine();
```

The output of the linux test server is.
![image](https://user-images.githubusercontent.com/6939810/80154445-dd85c280-85bf-11ea-9569-784a1815a3c4.png)

Unfortunately I cannot see why the gateway is not responding. I have no trace from the device but the coap-client test app works fine and is also able to communicate with the coap-server without issues.

I already pulled this source code and added some debug outputs. The real IKEA gateway returns the following records when connecting.

RECORD received: Handshake
RECORD received: Handshake
RECORD received: Alert DTLS.TAlertDescription.BadRecordMac

Do you have any idea what is going wrong? I tried to all all ciphers to the supported list but no luck. I also tried to set the protocol version to 1.0 but then I get an exception (cipher is null).

If you need more information please let me know.

Best regards
Christian

**Comment by kdurkin77** [comment]
I apologize, I was not getting notifications apparently and I never saw this. @chkr1011 were you able to resolve this?

**Comment by chkr1011** [comment]
I moved to another library which now works fine.
